#!/bin/csh -f 
set source1=./dmsm.f90
set source2=./dmsm.example.mpi.f90
set compiler=mpiifort
set ccompiler=mpiicc
set options=" -fopenmp -O3"
set library=" dmsm.ctimer.o "
set deletable="./*.o ./*.mod"
if(null$2 == null) then
   echo "hhm followed with total_number_of_processes and number_of_processes_for_each_job please."
   exit
endif

rm ./a.out 
dos2unix $source1 $source1
dos2unix $source2 $source2
$ccompiler $options -c dmsm.ctimer.c
$compiler -cpp $options -o ./a.out $source1 $source2 $library
rm $deletable
echo Please press the ENTER key to run with total processes $1, and $2 processes for a job
$<
echo $2 > MPI.PROCESSES.IN.JOB.COMM.dat
setenv PARALLEL 1
setenv OMP_NUM_THREADS 1
mpirun -np $1 ./a.out
exit


